Improve README for better guidance on how to use processors within NiFi (#21)
greymatter-io/nifi-sdk pull request #40
Opened 2020-11-03 20:36 UTC by TheMover

2020-11-03 20:42 UTC, dborncamp requested changes
It's good to have usage instructions! It would be good to note that they probably will not have pull access to anything in `deciphernow` or `greymatter.io` that the docker-compose references and send them to the website to get a demo https://greymatter.io/grey-matter

2020-11-09 15:23 UTC, dborncamp approved these changes

2020-11-19 19:02 UTC, lucasmoten commented
> It's good to have usage instructions! It would be good to note that they probably will not have pull access to anything in `deciphernow` or `greymatter.io` that the docker-compose references and send them to the website to get a demo https://greymatter.io/grey-matter

Agreed on the benefits offered for usage instructions.  Regarding the docker-compose concern for the images it references, there is a separate issue #13 opened for that.

2020-11-19 19:04 UTC, lucasmoten approved these changes

2020-12-08 21:23 UTC, merged